// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LynxaDeviceMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from LynxaDeviceMessages.proto</summary>
public static partial class LynxaDeviceMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for LynxaDeviceMessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LynxaDeviceMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlMeW54YURldmljZU1lc3NhZ2VzLnByb3RvGgxuYW5vcGIucHJvdG8i6wEK",
          "EEduZ2dhTWVzc2FnZV8xMDASEQoJZXBvY2hUaW1lGAEgAigNEhcKD2xhdGl0",
          "dWRlTWludXRlcxgEIAIoAhIXCg9sYXRpdHVkZURlZ3JlZXMYBSACKA0SHQoV",
          "bGF0aXR1ZGVDYXJkaW5hbEFzY2lpGAYgAigNEhgKEGxvbmdpdHVkZU1pbnV0",
          "ZXMYByACKAISGAoQbG9uZ2l0dWRlRGVncmVlcxgIIAIoDRIeChZsb25naXR1",
          "ZGVDYXJkaW5hbEFzY2lpGAkgAigNEh8KF251bWJlck9mU2F0ZWxsaXRlc0lu",
          "VXNlGAogAigNIj8KDkxvZ01lc3NhZ2VfMTAxEhEKCWVwb2NoVGltZRgBIAIo",
          "DRIaCgpsb2dNZXNzYWdlGAIgAigJQgaSPwNwgAEiNgoLV2lmaVN0YXRpb24S",
          "GQoFYnNzaWQYASACKAxCCpI/AggGkj8CeAESDAoEcnNzaRgCIAIoBSJwChNX",
          "aWZpU3RhdGlvbkxpc3RfMTAyEhEKCWVwb2NoVGltZRgBIAIoDRIbChNudW1i",
          "ZXJTdGF0aW9uc0ZvdW5kGAIgAigNEikKDHdpZmlTdGF0aW9ucxgDIAMoCzIM",
          "LldpZmlTdGF0aW9uQgWSPwIQDCJpChNNb2RlbVBhcmFtZXRlcnNfMTAzEhEK",
          "CWVwb2NoVGltZRgBIAIoDRIWCgdjZWxsX2lkGAIgAigJQgWSPwJwCBITCgRw",
          "bG1uGAMgAigJQgWSPwJwBhISCgN0YWMYBCACKAlCBZI/AnAD"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::NanopbReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GnggaMessage_100), global::GnggaMessage_100.Parser, new[]{ "EpochTime", "LatitudeMinutes", "LatitudeDegrees", "LatitudeCardinalAscii", "LongitudeMinutes", "LongitudeDegrees", "LongitudeCardinalAscii", "NumberOfSatellitesInUse" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LogMessage_101), global::LogMessage_101.Parser, new[]{ "EpochTime", "LogMessage" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WifiStation), global::WifiStation.Parser, new[]{ "Bssid", "Rssi" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WifiStationList_102), global::WifiStationList_102.Parser, new[]{ "EpochTime", "NumberStationsFound", "WifiStations" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ModemParameters_103), global::ModemParameters_103.Parser, new[]{ "EpochTime", "CellId", "Plmn", "Tac" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GnggaMessage_100 : pb::IMessage<GnggaMessage_100>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GnggaMessage_100> _parser = new pb::MessageParser<GnggaMessage_100>(() => new GnggaMessage_100());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<GnggaMessage_100> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LynxaDeviceMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GnggaMessage_100() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GnggaMessage_100(GnggaMessage_100 other) : this() {
    _hasBits0 = other._hasBits0;
    epochTime_ = other.epochTime_;
    latitudeMinutes_ = other.latitudeMinutes_;
    latitudeDegrees_ = other.latitudeDegrees_;
    latitudeCardinalAscii_ = other.latitudeCardinalAscii_;
    longitudeMinutes_ = other.longitudeMinutes_;
    longitudeDegrees_ = other.longitudeDegrees_;
    longitudeCardinalAscii_ = other.longitudeCardinalAscii_;
    numberOfSatellitesInUse_ = other.numberOfSatellitesInUse_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GnggaMessage_100 Clone() {
    return new GnggaMessage_100(this);
  }

  /// <summary>Field number for the "epochTime" field.</summary>
  public const int EpochTimeFieldNumber = 1;
  private readonly static uint EpochTimeDefaultValue = 0;

  private uint epochTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EpochTime {
    get { if ((_hasBits0 & 1) != 0) { return epochTime_; } else { return EpochTimeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      epochTime_ = value;
    }
  }
  /// <summary>Gets whether the "epochTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEpochTime {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "epochTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEpochTime() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "latitudeMinutes" field.</summary>
  public const int LatitudeMinutesFieldNumber = 4;
  private readonly static float LatitudeMinutesDefaultValue = 0F;

  private float latitudeMinutes_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float LatitudeMinutes {
    get { if ((_hasBits0 & 2) != 0) { return latitudeMinutes_; } else { return LatitudeMinutesDefaultValue; } }
    set {
      _hasBits0 |= 2;
      latitudeMinutes_ = value;
    }
  }
  /// <summary>Gets whether the "latitudeMinutes" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLatitudeMinutes {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "latitudeMinutes" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLatitudeMinutes() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "latitudeDegrees" field.</summary>
  public const int LatitudeDegreesFieldNumber = 5;
  private readonly static uint LatitudeDegreesDefaultValue = 0;

  private uint latitudeDegrees_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LatitudeDegrees {
    get { if ((_hasBits0 & 4) != 0) { return latitudeDegrees_; } else { return LatitudeDegreesDefaultValue; } }
    set {
      _hasBits0 |= 4;
      latitudeDegrees_ = value;
    }
  }
  /// <summary>Gets whether the "latitudeDegrees" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLatitudeDegrees {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "latitudeDegrees" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLatitudeDegrees() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "latitudeCardinalAscii" field.</summary>
  public const int LatitudeCardinalAsciiFieldNumber = 6;
  private readonly static uint LatitudeCardinalAsciiDefaultValue = 0;

  private uint latitudeCardinalAscii_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LatitudeCardinalAscii {
    get { if ((_hasBits0 & 8) != 0) { return latitudeCardinalAscii_; } else { return LatitudeCardinalAsciiDefaultValue; } }
    set {
      _hasBits0 |= 8;
      latitudeCardinalAscii_ = value;
    }
  }
  /// <summary>Gets whether the "latitudeCardinalAscii" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLatitudeCardinalAscii {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "latitudeCardinalAscii" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLatitudeCardinalAscii() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "longitudeMinutes" field.</summary>
  public const int LongitudeMinutesFieldNumber = 7;
  private readonly static float LongitudeMinutesDefaultValue = 0F;

  private float longitudeMinutes_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float LongitudeMinutes {
    get { if ((_hasBits0 & 16) != 0) { return longitudeMinutes_; } else { return LongitudeMinutesDefaultValue; } }
    set {
      _hasBits0 |= 16;
      longitudeMinutes_ = value;
    }
  }
  /// <summary>Gets whether the "longitudeMinutes" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLongitudeMinutes {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "longitudeMinutes" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLongitudeMinutes() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "longitudeDegrees" field.</summary>
  public const int LongitudeDegreesFieldNumber = 8;
  private readonly static uint LongitudeDegreesDefaultValue = 0;

  private uint longitudeDegrees_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LongitudeDegrees {
    get { if ((_hasBits0 & 32) != 0) { return longitudeDegrees_; } else { return LongitudeDegreesDefaultValue; } }
    set {
      _hasBits0 |= 32;
      longitudeDegrees_ = value;
    }
  }
  /// <summary>Gets whether the "longitudeDegrees" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLongitudeDegrees {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "longitudeDegrees" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLongitudeDegrees() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "longitudeCardinalAscii" field.</summary>
  public const int LongitudeCardinalAsciiFieldNumber = 9;
  private readonly static uint LongitudeCardinalAsciiDefaultValue = 0;

  private uint longitudeCardinalAscii_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LongitudeCardinalAscii {
    get { if ((_hasBits0 & 64) != 0) { return longitudeCardinalAscii_; } else { return LongitudeCardinalAsciiDefaultValue; } }
    set {
      _hasBits0 |= 64;
      longitudeCardinalAscii_ = value;
    }
  }
  /// <summary>Gets whether the "longitudeCardinalAscii" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLongitudeCardinalAscii {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "longitudeCardinalAscii" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLongitudeCardinalAscii() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "numberOfSatellitesInUse" field.</summary>
  public const int NumberOfSatellitesInUseFieldNumber = 10;
  private readonly static uint NumberOfSatellitesInUseDefaultValue = 0;

  private uint numberOfSatellitesInUse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint NumberOfSatellitesInUse {
    get { if ((_hasBits0 & 128) != 0) { return numberOfSatellitesInUse_; } else { return NumberOfSatellitesInUseDefaultValue; } }
    set {
      _hasBits0 |= 128;
      numberOfSatellitesInUse_ = value;
    }
  }
  /// <summary>Gets whether the "numberOfSatellitesInUse" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNumberOfSatellitesInUse {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "numberOfSatellitesInUse" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNumberOfSatellitesInUse() {
    _hasBits0 &= ~128;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as GnggaMessage_100);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(GnggaMessage_100 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EpochTime != other.EpochTime) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LatitudeMinutes, other.LatitudeMinutes)) return false;
    if (LatitudeDegrees != other.LatitudeDegrees) return false;
    if (LatitudeCardinalAscii != other.LatitudeCardinalAscii) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LongitudeMinutes, other.LongitudeMinutes)) return false;
    if (LongitudeDegrees != other.LongitudeDegrees) return false;
    if (LongitudeCardinalAscii != other.LongitudeCardinalAscii) return false;
    if (NumberOfSatellitesInUse != other.NumberOfSatellitesInUse) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEpochTime) hash ^= EpochTime.GetHashCode();
    if (HasLatitudeMinutes) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LatitudeMinutes);
    if (HasLatitudeDegrees) hash ^= LatitudeDegrees.GetHashCode();
    if (HasLatitudeCardinalAscii) hash ^= LatitudeCardinalAscii.GetHashCode();
    if (HasLongitudeMinutes) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LongitudeMinutes);
    if (HasLongitudeDegrees) hash ^= LongitudeDegrees.GetHashCode();
    if (HasLongitudeCardinalAscii) hash ^= LongitudeCardinalAscii.GetHashCode();
    if (HasNumberOfSatellitesInUse) hash ^= NumberOfSatellitesInUse.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasLatitudeMinutes) {
      output.WriteRawTag(37);
      output.WriteFloat(LatitudeMinutes);
    }
    if (HasLatitudeDegrees) {
      output.WriteRawTag(40);
      output.WriteUInt32(LatitudeDegrees);
    }
    if (HasLatitudeCardinalAscii) {
      output.WriteRawTag(48);
      output.WriteUInt32(LatitudeCardinalAscii);
    }
    if (HasLongitudeMinutes) {
      output.WriteRawTag(61);
      output.WriteFloat(LongitudeMinutes);
    }
    if (HasLongitudeDegrees) {
      output.WriteRawTag(64);
      output.WriteUInt32(LongitudeDegrees);
    }
    if (HasLongitudeCardinalAscii) {
      output.WriteRawTag(72);
      output.WriteUInt32(LongitudeCardinalAscii);
    }
    if (HasNumberOfSatellitesInUse) {
      output.WriteRawTag(80);
      output.WriteUInt32(NumberOfSatellitesInUse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasLatitudeMinutes) {
      output.WriteRawTag(37);
      output.WriteFloat(LatitudeMinutes);
    }
    if (HasLatitudeDegrees) {
      output.WriteRawTag(40);
      output.WriteUInt32(LatitudeDegrees);
    }
    if (HasLatitudeCardinalAscii) {
      output.WriteRawTag(48);
      output.WriteUInt32(LatitudeCardinalAscii);
    }
    if (HasLongitudeMinutes) {
      output.WriteRawTag(61);
      output.WriteFloat(LongitudeMinutes);
    }
    if (HasLongitudeDegrees) {
      output.WriteRawTag(64);
      output.WriteUInt32(LongitudeDegrees);
    }
    if (HasLongitudeCardinalAscii) {
      output.WriteRawTag(72);
      output.WriteUInt32(LongitudeCardinalAscii);
    }
    if (HasNumberOfSatellitesInUse) {
      output.WriteRawTag(80);
      output.WriteUInt32(NumberOfSatellitesInUse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEpochTime) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EpochTime);
    }
    if (HasLatitudeMinutes) {
      size += 1 + 4;
    }
    if (HasLatitudeDegrees) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LatitudeDegrees);
    }
    if (HasLatitudeCardinalAscii) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LatitudeCardinalAscii);
    }
    if (HasLongitudeMinutes) {
      size += 1 + 4;
    }
    if (HasLongitudeDegrees) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LongitudeDegrees);
    }
    if (HasLongitudeCardinalAscii) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LongitudeCardinalAscii);
    }
    if (HasNumberOfSatellitesInUse) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberOfSatellitesInUse);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(GnggaMessage_100 other) {
    if (other == null) {
      return;
    }
    if (other.HasEpochTime) {
      EpochTime = other.EpochTime;
    }
    if (other.HasLatitudeMinutes) {
      LatitudeMinutes = other.LatitudeMinutes;
    }
    if (other.HasLatitudeDegrees) {
      LatitudeDegrees = other.LatitudeDegrees;
    }
    if (other.HasLatitudeCardinalAscii) {
      LatitudeCardinalAscii = other.LatitudeCardinalAscii;
    }
    if (other.HasLongitudeMinutes) {
      LongitudeMinutes = other.LongitudeMinutes;
    }
    if (other.HasLongitudeDegrees) {
      LongitudeDegrees = other.LongitudeDegrees;
    }
    if (other.HasLongitudeCardinalAscii) {
      LongitudeCardinalAscii = other.LongitudeCardinalAscii;
    }
    if (other.HasNumberOfSatellitesInUse) {
      NumberOfSatellitesInUse = other.NumberOfSatellitesInUse;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 37: {
          LatitudeMinutes = input.ReadFloat();
          break;
        }
        case 40: {
          LatitudeDegrees = input.ReadUInt32();
          break;
        }
        case 48: {
          LatitudeCardinalAscii = input.ReadUInt32();
          break;
        }
        case 61: {
          LongitudeMinutes = input.ReadFloat();
          break;
        }
        case 64: {
          LongitudeDegrees = input.ReadUInt32();
          break;
        }
        case 72: {
          LongitudeCardinalAscii = input.ReadUInt32();
          break;
        }
        case 80: {
          NumberOfSatellitesInUse = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 37: {
          LatitudeMinutes = input.ReadFloat();
          break;
        }
        case 40: {
          LatitudeDegrees = input.ReadUInt32();
          break;
        }
        case 48: {
          LatitudeCardinalAscii = input.ReadUInt32();
          break;
        }
        case 61: {
          LongitudeMinutes = input.ReadFloat();
          break;
        }
        case 64: {
          LongitudeDegrees = input.ReadUInt32();
          break;
        }
        case 72: {
          LongitudeCardinalAscii = input.ReadUInt32();
          break;
        }
        case 80: {
          NumberOfSatellitesInUse = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LogMessage_101 : pb::IMessage<LogMessage_101>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LogMessage_101> _parser = new pb::MessageParser<LogMessage_101>(() => new LogMessage_101());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<LogMessage_101> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LynxaDeviceMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LogMessage_101() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LogMessage_101(LogMessage_101 other) : this() {
    _hasBits0 = other._hasBits0;
    epochTime_ = other.epochTime_;
    logMessage_ = other.logMessage_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LogMessage_101 Clone() {
    return new LogMessage_101(this);
  }

  /// <summary>Field number for the "epochTime" field.</summary>
  public const int EpochTimeFieldNumber = 1;
  private readonly static uint EpochTimeDefaultValue = 0;

  private uint epochTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EpochTime {
    get { if ((_hasBits0 & 1) != 0) { return epochTime_; } else { return EpochTimeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      epochTime_ = value;
    }
  }
  /// <summary>Gets whether the "epochTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEpochTime {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "epochTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEpochTime() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "logMessage" field.</summary>
  public const int LogMessageFieldNumber = 2;
  private readonly static string LogMessageDefaultValue = "";

  private string logMessage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LogMessage {
    get { return logMessage_ ?? LogMessageDefaultValue; }
    set {
      logMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "logMessage" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLogMessage {
    get { return logMessage_ != null; }
  }
  /// <summary>Clears the value of the "logMessage" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLogMessage() {
    logMessage_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as LogMessage_101);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(LogMessage_101 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EpochTime != other.EpochTime) return false;
    if (LogMessage != other.LogMessage) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEpochTime) hash ^= EpochTime.GetHashCode();
    if (HasLogMessage) hash ^= LogMessage.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasLogMessage) {
      output.WriteRawTag(18);
      output.WriteString(LogMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasLogMessage) {
      output.WriteRawTag(18);
      output.WriteString(LogMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEpochTime) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EpochTime);
    }
    if (HasLogMessage) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LogMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(LogMessage_101 other) {
    if (other == null) {
      return;
    }
    if (other.HasEpochTime) {
      EpochTime = other.EpochTime;
    }
    if (other.HasLogMessage) {
      LogMessage = other.LogMessage;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 18: {
          LogMessage = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 18: {
          LogMessage = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class WifiStation : pb::IMessage<WifiStation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WifiStation> _parser = new pb::MessageParser<WifiStation>(() => new WifiStation());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WifiStation> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LynxaDeviceMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStation() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStation(WifiStation other) : this() {
    _hasBits0 = other._hasBits0;
    bssid_ = other.bssid_;
    rssi_ = other.rssi_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStation Clone() {
    return new WifiStation(this);
  }

  /// <summary>Field number for the "bssid" field.</summary>
  public const int BssidFieldNumber = 1;
  private readonly static pb::ByteString BssidDefaultValue = pb::ByteString.Empty;

  private pb::ByteString bssid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Bssid {
    get { return bssid_ ?? BssidDefaultValue; }
    set {
      bssid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "bssid" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasBssid {
    get { return bssid_ != null; }
  }
  /// <summary>Clears the value of the "bssid" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearBssid() {
    bssid_ = null;
  }

  /// <summary>Field number for the "rssi" field.</summary>
  public const int RssiFieldNumber = 2;
  private readonly static int RssiDefaultValue = 0;

  private int rssi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Rssi {
    get { if ((_hasBits0 & 1) != 0) { return rssi_; } else { return RssiDefaultValue; } }
    set {
      _hasBits0 |= 1;
      rssi_ = value;
    }
  }
  /// <summary>Gets whether the "rssi" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRssi {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "rssi" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRssi() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WifiStation);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WifiStation other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Bssid != other.Bssid) return false;
    if (Rssi != other.Rssi) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasBssid) hash ^= Bssid.GetHashCode();
    if (HasRssi) hash ^= Rssi.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasBssid) {
      output.WriteRawTag(10);
      output.WriteBytes(Bssid);
    }
    if (HasRssi) {
      output.WriteRawTag(16);
      output.WriteInt32(Rssi);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasBssid) {
      output.WriteRawTag(10);
      output.WriteBytes(Bssid);
    }
    if (HasRssi) {
      output.WriteRawTag(16);
      output.WriteInt32(Rssi);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasBssid) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bssid);
    }
    if (HasRssi) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rssi);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WifiStation other) {
    if (other == null) {
      return;
    }
    if (other.HasBssid) {
      Bssid = other.Bssid;
    }
    if (other.HasRssi) {
      Rssi = other.Rssi;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Bssid = input.ReadBytes();
          break;
        }
        case 16: {
          Rssi = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Bssid = input.ReadBytes();
          break;
        }
        case 16: {
          Rssi = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class WifiStationList_102 : pb::IMessage<WifiStationList_102>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WifiStationList_102> _parser = new pb::MessageParser<WifiStationList_102>(() => new WifiStationList_102());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WifiStationList_102> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LynxaDeviceMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStationList_102() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStationList_102(WifiStationList_102 other) : this() {
    _hasBits0 = other._hasBits0;
    epochTime_ = other.epochTime_;
    numberStationsFound_ = other.numberStationsFound_;
    wifiStations_ = other.wifiStations_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WifiStationList_102 Clone() {
    return new WifiStationList_102(this);
  }

  /// <summary>Field number for the "epochTime" field.</summary>
  public const int EpochTimeFieldNumber = 1;
  private readonly static uint EpochTimeDefaultValue = 0;

  private uint epochTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EpochTime {
    get { if ((_hasBits0 & 1) != 0) { return epochTime_; } else { return EpochTimeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      epochTime_ = value;
    }
  }
  /// <summary>Gets whether the "epochTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEpochTime {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "epochTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEpochTime() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "numberStationsFound" field.</summary>
  public const int NumberStationsFoundFieldNumber = 2;
  private readonly static uint NumberStationsFoundDefaultValue = 0;

  private uint numberStationsFound_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint NumberStationsFound {
    get { if ((_hasBits0 & 2) != 0) { return numberStationsFound_; } else { return NumberStationsFoundDefaultValue; } }
    set {
      _hasBits0 |= 2;
      numberStationsFound_ = value;
    }
  }
  /// <summary>Gets whether the "numberStationsFound" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNumberStationsFound {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "numberStationsFound" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNumberStationsFound() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "wifiStations" field.</summary>
  public const int WifiStationsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::WifiStation> _repeated_wifiStations_codec
      = pb::FieldCodec.ForMessage(26, global::WifiStation.Parser);
  private readonly pbc::RepeatedField<global::WifiStation> wifiStations_ = new pbc::RepeatedField<global::WifiStation>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::WifiStation> WifiStations {
    get { return wifiStations_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WifiStationList_102);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WifiStationList_102 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EpochTime != other.EpochTime) return false;
    if (NumberStationsFound != other.NumberStationsFound) return false;
    if(!wifiStations_.Equals(other.wifiStations_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEpochTime) hash ^= EpochTime.GetHashCode();
    if (HasNumberStationsFound) hash ^= NumberStationsFound.GetHashCode();
    hash ^= wifiStations_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasNumberStationsFound) {
      output.WriteRawTag(16);
      output.WriteUInt32(NumberStationsFound);
    }
    wifiStations_.WriteTo(output, _repeated_wifiStations_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasNumberStationsFound) {
      output.WriteRawTag(16);
      output.WriteUInt32(NumberStationsFound);
    }
    wifiStations_.WriteTo(ref output, _repeated_wifiStations_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEpochTime) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EpochTime);
    }
    if (HasNumberStationsFound) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumberStationsFound);
    }
    size += wifiStations_.CalculateSize(_repeated_wifiStations_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WifiStationList_102 other) {
    if (other == null) {
      return;
    }
    if (other.HasEpochTime) {
      EpochTime = other.EpochTime;
    }
    if (other.HasNumberStationsFound) {
      NumberStationsFound = other.NumberStationsFound;
    }
    wifiStations_.Add(other.wifiStations_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 16: {
          NumberStationsFound = input.ReadUInt32();
          break;
        }
        case 26: {
          wifiStations_.AddEntriesFrom(input, _repeated_wifiStations_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 16: {
          NumberStationsFound = input.ReadUInt32();
          break;
        }
        case 26: {
          wifiStations_.AddEntriesFrom(ref input, _repeated_wifiStations_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ModemParameters_103 : pb::IMessage<ModemParameters_103>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ModemParameters_103> _parser = new pb::MessageParser<ModemParameters_103>(() => new ModemParameters_103());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ModemParameters_103> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LynxaDeviceMessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ModemParameters_103() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ModemParameters_103(ModemParameters_103 other) : this() {
    _hasBits0 = other._hasBits0;
    epochTime_ = other.epochTime_;
    cellId_ = other.cellId_;
    plmn_ = other.plmn_;
    tac_ = other.tac_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ModemParameters_103 Clone() {
    return new ModemParameters_103(this);
  }

  /// <summary>Field number for the "epochTime" field.</summary>
  public const int EpochTimeFieldNumber = 1;
  private readonly static uint EpochTimeDefaultValue = 0;

  private uint epochTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint EpochTime {
    get { if ((_hasBits0 & 1) != 0) { return epochTime_; } else { return EpochTimeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      epochTime_ = value;
    }
  }
  /// <summary>Gets whether the "epochTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasEpochTime {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "epochTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearEpochTime() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "cell_id" field.</summary>
  public const int CellIdFieldNumber = 2;
  private readonly static string CellIdDefaultValue = "";

  private string cellId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CellId {
    get { return cellId_ ?? CellIdDefaultValue; }
    set {
      cellId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "cell_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCellId {
    get { return cellId_ != null; }
  }
  /// <summary>Clears the value of the "cell_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCellId() {
    cellId_ = null;
  }

  /// <summary>Field number for the "plmn" field.</summary>
  public const int PlmnFieldNumber = 3;
  private readonly static string PlmnDefaultValue = "";

  private string plmn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Plmn {
    get { return plmn_ ?? PlmnDefaultValue; }
    set {
      plmn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "plmn" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlmn {
    get { return plmn_ != null; }
  }
  /// <summary>Clears the value of the "plmn" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlmn() {
    plmn_ = null;
  }

  /// <summary>Field number for the "tac" field.</summary>
  public const int TacFieldNumber = 4;
  private readonly static string TacDefaultValue = "";

  private string tac_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Tac {
    get { return tac_ ?? TacDefaultValue; }
    set {
      tac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "tac" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasTac {
    get { return tac_ != null; }
  }
  /// <summary>Clears the value of the "tac" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearTac() {
    tac_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ModemParameters_103);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ModemParameters_103 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EpochTime != other.EpochTime) return false;
    if (CellId != other.CellId) return false;
    if (Plmn != other.Plmn) return false;
    if (Tac != other.Tac) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasEpochTime) hash ^= EpochTime.GetHashCode();
    if (HasCellId) hash ^= CellId.GetHashCode();
    if (HasPlmn) hash ^= Plmn.GetHashCode();
    if (HasTac) hash ^= Tac.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasCellId) {
      output.WriteRawTag(18);
      output.WriteString(CellId);
    }
    if (HasPlmn) {
      output.WriteRawTag(26);
      output.WriteString(Plmn);
    }
    if (HasTac) {
      output.WriteRawTag(34);
      output.WriteString(Tac);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasEpochTime) {
      output.WriteRawTag(8);
      output.WriteUInt32(EpochTime);
    }
    if (HasCellId) {
      output.WriteRawTag(18);
      output.WriteString(CellId);
    }
    if (HasPlmn) {
      output.WriteRawTag(26);
      output.WriteString(Plmn);
    }
    if (HasTac) {
      output.WriteRawTag(34);
      output.WriteString(Tac);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasEpochTime) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EpochTime);
    }
    if (HasCellId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CellId);
    }
    if (HasPlmn) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Plmn);
    }
    if (HasTac) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Tac);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ModemParameters_103 other) {
    if (other == null) {
      return;
    }
    if (other.HasEpochTime) {
      EpochTime = other.EpochTime;
    }
    if (other.HasCellId) {
      CellId = other.CellId;
    }
    if (other.HasPlmn) {
      Plmn = other.Plmn;
    }
    if (other.HasTac) {
      Tac = other.Tac;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 18: {
          CellId = input.ReadString();
          break;
        }
        case 26: {
          Plmn = input.ReadString();
          break;
        }
        case 34: {
          Tac = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EpochTime = input.ReadUInt32();
          break;
        }
        case 18: {
          CellId = input.ReadString();
          break;
        }
        case 26: {
          Plmn = input.ReadString();
          break;
        }
        case 34: {
          Tac = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
