/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "LynxaDeviceMessages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GnggaMessage_100, GnggaMessage_100, AUTO)


PB_BIND(LogMessage_101, LogMessage_101, AUTO)


PB_BIND(WifiStation, WifiStation, AUTO)


PB_BIND(WifiStationList_102, WifiStationList_102, AUTO)


PB_BIND(CellTower, CellTower, AUTO)


PB_BIND(GoogleLocationServices_102, GoogleLocationServices_102, AUTO)



